Reorder shutdown routines
aiokitchen/aiomisc pull request #126
Opened 2021-11-25 21:13 UTC by tzoiker

With the current order of shutdown routines some unexpected behaviour may happen within signal subscribers, 

`PRE_START (setup some background tasks) -> start -> stop -> graceful shutdown -> cancel all background tasks -> POST_STOP (something relying on background tasks breaks here)`.

Propose to cleanup all background tasks after `POST_STOP`.

2021-11-25 21:40 UTC, mosquito approved these changes

2021-11-26 08:39 UTC, dizballanze requested changes

2021-11-26 08:39 UTC, dizballanze commented on requirements.dev.txt
> +aiomisc-dependency==0.1.17
Let's make tests without aimoisc-dependency

2021-11-26 21:27 UTC, tzoiker commented on requirements.dev.txt
> +aiomisc-dependency==0.1.17
\+

2021-11-27 08:56 UTC, dizballanze approved these changes

2021-12-14 18:00 UTC, merged