Feature Worker Pools
aiokitchen/aiomisc pull request #99
Opened 2021-03-26 08:31 UTC by mosquito

2021-03-29 15:58 UTC, Pavkazzz requested changes

2021-03-29 15:58 UTC, Pavkazzz commented on aiomisc/worker_pool.py
> +    def step() -> Optional[bool]:
just bool is ok here

2021-03-29 15:58 UTC, Pavkazzz commented on aiomisc/worker_pool.py
> +            await asyncio.sleep(0.1)
Mb give ability to configure sleep time?

2021-04-01 08:53 UTC, dizballanze requested changes

2021-04-01 08:53 UTC, dizballanze commented on aiomisc/worker_pool/pool.py
> +            await writer.drain()
why?

2021-04-01 08:53 UTC, dizballanze commented on aiomisc/worker_pool/pool.py
> +        )
I think debug log with process id can be useful here

2021-04-01 08:53 UTC, dizballanze commented on aiomisc/worker_pool/pool.py
> +        process.kill()
Debug log here

2021-04-01 08:53 UTC, dizballanze commented on aiomisc/worker_pool/process.py
> +from typing import Tuple, Union, Any
empty line missed

2021-04-01 08:53 UTC, dizballanze commented on aiomisc/worker_pool/process.py
> +        logging.debug("Connecting...")
add pid here and probably in all logs in this module

2021-04-01 08:53 UTC, dizballanze commented on docs/source/locale/ru/LC_MESSAGES/worker_pool.po
> +"separate processes no asynchronous."
aren't asynchronous

2021-04-01 08:53 UTC, dizballanze commented on docs/source/locale/ru/LC_MESSAGES/worker_pool.po
> +"This very be useful when you want to process data in separate process but"
This will be useful

2021-04-01 08:53 UTC, dizballanze commented on docs/source/locale/ru/LC_MESSAGES/worker_pool.po
> +"thumbnails for this. In this case you have the file with original image "
for this -> for them

2021-04-01 08:53 UTC, dizballanze commented on docs/source/locale/ru/LC_MESSAGES/worker_pool.po
> +msgid "You have to install Pollow image processing library for run this example."
Pollow -> Pillow
for run -> to run

2021-04-01 08:53 UTC, dizballanze commented on tests/test_worker_pool.py
> +    assert results == [i * i for i in range(worker_pool.workers * 2)]
`assert sorted(results) == ...` no need for variable change

2021-04-12 12:56 UTC, dizballanze approved these changes

2021-04-12 17:08 UTC, alvassin requested changes

2021-04-27 12:12 UTC, Pavkazzz approved these changes

2021-04-27 12:29 UTC, merged